version: '3'
services:
  db:
    container_name: 'rails-db'
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - rails-network

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - rails-network

networks:
  rails-network:
    driver: bridge